baseurl = "http://mgmtconfig.org/"
languageCode = "en-us"
title = "MGMTconfig"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "James"
	description = "mgmt: next generation config management!"
	copyright = "Released under the GNU license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/purpleidea/mgmt"

	version = "0.0.4"
	logo = "images/logo1.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "indigo"
    	accent  = "blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "mgmtconfig"
	github  = "purpleidea"
	irc 		= "mgmtconfig"
#	email   = "hello@email.com"


[[menu.main]]
	name   = "MGMT"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Concepts"
	url    = "concepts/"
	weight = 20

[[menu.main]]
	name   = "Features"
	url    = "features/"
	weight = 30

[[menu.main]]
	name   = "Resources"
	url    = "resources/"
	weight = 40

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 80

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 90

[[menu.main]]
	name   = "FAQ"
	url    = "faq/"
	weight = 99


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
